### ISSUE TITLE
配置出错

### ISSUE THREAD

**Issue by 1925197339** [Anmizi/WXmusic_miniprogram#1]
可以看看你的完整展示吗？我在本地配置的时候 http://codercba.com:9002 这个网易云的接口，没办法配置，它不是https协议，调用不了这个接口，都报错，后面也有一系列的请求错误，希望与作者讨论一下

**Comment by Anmizi** [comment]
![image](https://github.com/Anmizi/WXmusic_miniprogram/assets/69138726/924f119e-ad7b-4b4f-9925-1739f1c35828)
本地开发时，这个选项勾选一下，因为域名不是我自己的，我也是用的别人的接口

**Comment by 1925197339** [comment]
勾选了这个选项，也在后台去配置了这个地址，但是还是会报错，目前我还没有这个能力去自己解决，哈哈哈哈






啊哈哈
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Anmizi/WXmusic_miniprogram"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月3日(星期六) 晚上9:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Anmizi/WXmusic_miniprogram] 配置出错 (Issue #1)





 

 本地开发时，这个选项勾选一下，因为域名不是我自己的，我也是用的别人的接口

**Comment by Anmizi** [comment]
@1925197339 报错的截图发一下

**Comment by 1925197339** [comment]
上封邮件中附有报错截图的啊



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月3日(周六) 晚上10:07
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Anmizi/WXmusic_miniprogram] 配置出错 (Issue #1)




 
@1925197339 报错的截图发一下

**Comment by Anmizi** [comment]
没有，你直接在issue里面发就行，截图复制粘贴就行

**Comment by Anmizi** [comment]
建议你看下README

**Comment by 1925197339** [comment]
![截图1](https://github.com/Anmizi/WXmusic_miniprogram/assets/130352695/f2fe2bf7-a91b-40df-af55-63e1456ad377)
![截图2](https://github.com/Anmizi/WXmusic_miniprogram/assets/130352695/70100586-7a32-4a95-8cfa-64ea5bd1ec90)
报错信息，README中的信息不起作用

**Comment by Anmizi** [comment]
这个域名不是你的，你是不能在微信小程序管理后台配置的，如果你自己要在线上部署，要用自己的域名部署
